### ISSUE TITLE
Ticker infrastructure

### ISSUE THREAD

**Issue by delahee** [nadako/haxe-coroutines#9]
Some languages/runtime don't have a proper ticker infrastructure to run the await stuffs.

Would you be kind and propose a basic Ticker proposal so that every "runtime" become aware they need to fill in this infrastructure to obtain a proprr promise/async/yield setup? 

Personnaly, being a metal guy, I don't really have an opinion on syntax as long as it's typed and brand futuristic enough... but the ticker implementations and the potential allocations should be in the clear so we know the overhead by reading the docs :)

Thanks!

**Comment by nadako** [comment]
I think that's out of scope of this proposal, since this design basically is only about the coroutine AST transformation and interaction protocol, which can then be integrated in any custom "ticker" or existing scheduling system. I might look into providing an example of such an integration using Nicolas' MainLoop thingy...

**Comment by delahee** [comment]
Thanks :)
